// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmyfzfhphjjhxgyxbgnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpteWZ6ZmhwaGpqaHhneXhiZ25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2ODk1NjYsImV4cCI6MjA2OTI2NTU2Nn0.WgRwIkiiZCYIGXNCSllIjTqUXh60uMFP0gKlf_ZcsVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});